version: '3.4'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
      - bycoderstec
    tty: true
    ports:
      - 8080:80

  cnab-file-db:
    image: mysql:latest
    container_name: cnab-file-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnab_file
      MYSQL_ROOT_HOST: '%' 
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose: 
      - 3307
    volumes:      
      - ./mysql/cnab-file-db:/var/lib/mysql
    networks:
      - bycoderstec
      
  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube
    environment:
      SONAR_WEB_CONTEXT: /sonarqube
    ports:
      - 9000:9000
    volumes:      
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - bycoderstec  

  cnab-backend:
    build:
      context: ./cnab-file-api
      dockerfile: Dockerfile
    image: cnab-backend
    restart: always
    container_name: cnab-backend
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://cnab-file-db:3307/cnab_file?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.FLYWAY.URL: jdbc:mysql://cnab-file-db:3307/cnab_file?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: root
      SERVER.PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - cnab-file-db
    networks:
      - bycoderstec      
  
  cnab-frontend:
    build:
      context: ./frontend  
    container_name: cnab-frontend  
    environment:
      REACT_APP_API_BASE: http://nginx:8080/cnab-backend
    networks:
      - bycoderstec
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    ports: 
      - 3000:3000

networks:
  bycoderstec:
    driver: bridge 