version: '3.4'

services:
  cnab-file-db:
    image: mysql:latest
    container_name: cnab-file-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnab_file
      MYSQL_ROOT_HOST: '%' 
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose: 
      - 3307
    volumes:      
      - ./mysql/cnab-file-db:/var/lib/mysql
    networks:
      - bycoderstec
      
  sonarque:
    image: sonarqube:8.9-community
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:      
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - bycoderstec  

  cnab-file-api:
    build:
      context: ./cnab-file-api
      dockerfile: Dockerfile
    image: cnab-file-api
    restart: always
    container_name: cnab-file-api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://cnab-file-db:3307/cnab_file?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.FLYWAY.URL: jdbc:mysql://cnab-file-db:3307/cnab_file?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: root
      SERVER.PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - cnab-file-db
    networks:
      - bycoderstec
      
networks:
  bycoderstec:
    driver: bridge 